package edu.syr.smalltalk.service.android.constant

object EntityConstant {
    const val FILE_INFO_FILE_ID = "file_id"
    const val FILE_INFO_FIRST_SELECTOR = "first_selector"
    const val FILE_INFO_SECOND_SELECTOR = "second_selector"
    const val FILE_INFO_FILE_NAME = "file_name"
    const val FILE_INFO_FILE_LINK = "file_link"
    const val FILE_INFO_FILE_UPLOADER = "file_uploader"
    const val FILE_INFO_FILE_UPLOAD_TIME = "file_upload_time"
    const val FILE_INFO_FILE_EXPIRE_TIME = "file_expire_time"
    const val FILE_INFO_FILE_SIZE = "file_size"
    const val FILE_INFO_FILE_DOWNLOADS = "file_downloads"
    const val GROUP_INFO_GROUP_ID = "group_id"
    const val GROUP_INFO_GROUP_HOST_ID = "group_host_id"
    const val GROUP_INFO_GROUP_NAME = "group_name"
    const val GROUP_INFO_GROUP_INFO = "group_info"
    const val GROUP_INFO_GROUP_AVATAR_LINK = "group_avatar_link"
    const val GROUP_INFO_MEMBER_LIST = "member_list"
    const val REQUEST_INFO_REQUEST_ID = "request_id"
    const val REQUEST_INFO_REQUEST_STATUS = "request_status"
    const val REQUEST_INFO_REQUEST_TYPE = "request_type"
    const val REQUEST_INFO_REQUEST_METADATA = "request_metadata"
    const val USER_INFO_USER_ID = "user_id"
    const val USER_INFO_USER_SESSION = "user_session"
    const val USER_INFO_USER_EMAIL = "user_email"
    const val USER_INFO_USER_NAME = "user_name"
    const val USER_INFO_USER_PASSWORD = "user_password"
    const val USER_INFO_USER_GENDER = "user_gender"
    const val USER_INFO_USER_AVATAR_LINK = "user_avatar_link"
    const val USER_INFO_USER_INFO = "user_info"
    const val USER_INFO_USER_LOCATION = "user_location"
    const val USER_INFO_USER_CONTACT_LIST = "user_contact_list"
    const val USER_INFO_USER_GROUP_LIST = "user_group_list"
    const val USER_INFO_USER_REQUEST_LIST = "user_request_list"
    const val CONTACT_INFO_CONTACT_ID = "contact_id"
    const val CONTACT_INFO_CONTACT_EMAIL = "contact_email"
    const val CONTACT_INFO_CONTACT_NAME = "contact_name"
    const val CONTACT_INFO_CONTACT_GENDER = "contact_gender"
    const val CONTACT_INFO_CONTACT_AVATAR_LINK = "contact_avatar_link"
    const val CONTACT_INFO_CONTACT_INFO = "contact_info"
    const val CONTACT_INFO_CONTACT_LOCATION = "contact_location"
}